# Generated by Django 5.1.4 on 2025-01-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_api', '0001_initial'),
        ('student_api', '0002_student_skillid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skillId',
        ),
        migrations.AddField(
            model_name='student',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='skill_api.skill'),
            preserve_default=False,
        ),
    ]
